version: '3'

services:

  auth-service:
    build:
      context: ./../services/auth
      dockerfile: ./../auth/authentication-service.dockerfile
    restart: always
    ports:
      - "9000:9000"
    deploy:
      mode: replicated
      replicas: 1
